#!/usr/bin/env bash
# setup_epic_fhir.sh — Configure Epic FHIR R4 OAuth2 credentials and test connection
# Usage:
#   ./setup_epic_fhir.sh                   # interactive setup
#   ./setup_epic_fhir.sh --env .env.fhir   # load from existing env file
#   ./setup_epic_fhir.sh --test-only       # validate existing credentials
#
# Requires: curl, jq (install: brew install jq  or  apt-get install jq)

set -euo pipefail
IFS=$'\n\t'

# ── Constants ─────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env.fhir"
TOKEN_CACHE="${REPO_ROOT}/.fhir_token_cache"
LOG_FILE="${REPO_ROOT}/logs/setup_epic_fhir.log"
EPIC_FHIR_VERSION="R4"
DEFAULT_FHIR_BASE="https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4"
SANDBOX_FHIR_BASE="https://fhir.epic.com/interconnect-fhir-oauth/oauth2/token"

# ANSI colours
RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
CYAN='\033[0;36m'; NC='\033[0m'; BOLD='\033[1m'

# ── Helpers ───────────────────────────────────────────────────────────────────

log() { echo -e "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "${LOG_FILE}"; }
info()    { log "${CYAN}INFO${NC}  $*"; }
success() { log "${GREEN}OK${NC}    $*"; }
warn()    { log "${YELLOW}WARN${NC}  $*"; }
error()   { log "${RED}ERROR${NC} $*" >&2; }
die()     { error "$*"; exit 1; }

check_dependency() {
  local cmd="$1"
  if ! command -v "${cmd}" &>/dev/null; then
    die "Required tool '${cmd}' not found. Install it and retry."
  fi
}

# ── Init ──────────────────────────────────────────────────────────────────────

mkdir -p "${REPO_ROOT}/logs"
touch "${LOG_FILE}"

check_dependency curl
check_dependency jq

# ── Argument parsing ──────────────────────────────────────────────────────────

ENV_FILE_ARG=""
TEST_ONLY=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)        ENV_FILE_ARG="$2"; shift 2 ;;
    --test-only)  TEST_ONLY=true; shift ;;
    -h|--help)
      grep '^#' "${BASH_SOURCE[0]}" | head -8 | sed 's/^# \?//'
      exit 0 ;;
    *) die "Unknown argument: $1" ;;
  esac
done

[[ -n "${ENV_FILE_ARG}" ]] && ENV_FILE="${ENV_FILE_ARG}"

# ── Load or prompt for credentials ───────────────────────────────────────────

load_env_file() {
  if [[ -f "${ENV_FILE}" ]]; then
    info "Loading credentials from ${ENV_FILE}"
    # shellcheck disable=SC1090
    set -o allexport
    source "${ENV_FILE}"
    set +o allexport
    return 0
  fi
  return 1
}

prompt_credentials() {
  echo -e "\n${BOLD}Epic FHIR R4 OAuth2 Setup${NC}"
  echo "─────────────────────────────────────────────────────"
  echo "You will need credentials from your Epic App Orchard registration."
  echo "For sandbox testing, use: https://fhir.epic.com/Developer/Apps"
  echo ""

  read -rp "Epic Client ID:            " EPIC_CLIENT_ID
  read -rsp "Epic Client Secret:        " EPIC_CLIENT_SECRET
  echo ""
  read -rp "Epic FHIR Base URL         [${DEFAULT_FHIR_BASE}]: " EPIC_FHIR_BASE_URL
  EPIC_FHIR_BASE_URL="${EPIC_FHIR_BASE_URL:-${DEFAULT_FHIR_BASE}}"
  read -rp "OAuth2 Token Endpoint      [${SANDBOX_FHIR_BASE}]: " EPIC_TOKEN_URL
  EPIC_TOKEN_URL="${EPIC_TOKEN_URL:-${SANDBOX_FHIR_BASE}}"
  read -rp "Scopes (space-separated)   [launch patient/*.read]: " EPIC_SCOPES
  EPIC_SCOPES="${EPIC_SCOPES:-launch patient/*.read}"
  read -rp "Organization ID (optional): " EPIC_ORG_ID
  EPIC_ORG_ID="${EPIC_ORG_ID:-}"

  [[ -z "${EPIC_CLIENT_ID}" ]] && die "Client ID cannot be empty."
  [[ -z "${EPIC_CLIENT_SECRET}" ]] && die "Client Secret cannot be empty."
}

save_env_file() {
  cat > "${ENV_FILE}" <<EOF
# Epic FHIR R4 OAuth2 credentials — generated by setup_epic_fhir.sh
# DO NOT commit this file to version control.
EPIC_CLIENT_ID="${EPIC_CLIENT_ID}"
EPIC_CLIENT_SECRET="${EPIC_CLIENT_SECRET}"
EPIC_FHIR_BASE_URL="${EPIC_FHIR_BASE_URL}"
EPIC_TOKEN_URL="${EPIC_TOKEN_URL}"
EPIC_SCOPES="${EPIC_SCOPES}"
EPIC_ORG_ID="${EPIC_ORG_ID:-}"
EPIC_FHIR_VERSION="${EPIC_FHIR_VERSION}"
EOF
  chmod 600 "${ENV_FILE}"
  success "Credentials saved to ${ENV_FILE} (mode 600)"
}

ensure_gitignore() {
  local gi="${REPO_ROOT}/.gitignore"
  local pattern=".env.fhir"
  if ! grep -qF "${pattern}" "${gi}" 2>/dev/null; then
    echo "${pattern}" >> "${gi}"
    echo ".fhir_token_cache" >> "${gi}"
    info "Added ${pattern} to .gitignore"
  fi
}

# ── OAuth2 Token Exchange ─────────────────────────────────────────────────────

fetch_access_token() {
  info "Requesting OAuth2 access token from ${EPIC_TOKEN_URL} …"

  local response
  response=$(curl --silent --show-error --fail \
    --max-time 30 \
    -X POST "${EPIC_TOKEN_URL}" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    --data-urlencode "grant_type=client_credentials" \
    --data-urlencode "client_id=${EPIC_CLIENT_ID}" \
    --data-urlencode "client_secret=${EPIC_CLIENT_SECRET}" \
    --data-urlencode "scope=${EPIC_SCOPES}" \
    2>&1) || {
    die "Token request failed. Check credentials and endpoint URL."
  }

  local error
  error=$(echo "${response}" | jq -r '.error // empty' 2>/dev/null || true)
  [[ -n "${error}" ]] && die "OAuth2 error: ${error} — $(echo "${response}" | jq -r '.error_description // ""')"

  ACCESS_TOKEN=$(echo "${response}" | jq -r '.access_token' 2>/dev/null)
  local expires_in
  expires_in=$(echo "${response}" | jq -r '.expires_in // 3600' 2>/dev/null)

  [[ -z "${ACCESS_TOKEN}" || "${ACCESS_TOKEN}" == "null" ]] && die "No access_token in response: ${response}"

  # Cache token with expiry
  cat > "${TOKEN_CACHE}" <<CACHE
ACCESS_TOKEN="${ACCESS_TOKEN}"
EXPIRES_AT="$(($(date +%s) + expires_in - 60))"
CACHE
  chmod 600 "${TOKEN_CACHE}"
  success "Access token acquired (expires in ${expires_in}s)"
}

load_cached_token() {
  if [[ -f "${TOKEN_CACHE}" ]]; then
    # shellcheck disable=SC1090
    source "${TOKEN_CACHE}"
    local now
    now=$(date +%s)
    if [[ "${now}" -lt "${EXPIRES_AT:-0}" ]]; then
      info "Using cached access token (valid for $((EXPIRES_AT - now))s)"
      return 0
    fi
  fi
  return 1
}

# ── FHIR R4 Connection Tests ──────────────────────────────────────────────────

test_capability_statement() {
  info "Fetching CapabilityStatement from ${EPIC_FHIR_BASE_URL}/metadata …"

  local response http_code
  http_code=$(curl --silent --output /dev/null --write-out "%{http_code}" \
    --max-time 30 \
    "${EPIC_FHIR_BASE_URL}/metadata" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" \
    -H "Accept: application/fhir+json") || true

  if [[ "${http_code}" == "200" ]]; then
    success "CapabilityStatement endpoint reachable (HTTP ${http_code})"
  else
    warn "Unexpected HTTP ${http_code} from /metadata — check base URL"
  fi
}

pull_sample_patient_notes() {
  info "Pulling sample DocumentReference (clinical notes) from FHIR R4 …"

  local url="${EPIC_FHIR_BASE_URL}/DocumentReference?category=clinical-note&_count=5&_sort=-date"
  local response http_code

  response=$(curl --silent --show-error \
    --max-time 30 \
    --write-out "\nHTTP_STATUS:%{http_code}" \
    "${url}" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" \
    -H "Accept: application/fhir+json") || {
    warn "DocumentReference request failed — may need additional scopes"
    return 1
  }

  http_code=$(echo "${response}" | grep "HTTP_STATUS:" | cut -d: -f2)
  local body
  body=$(echo "${response}" | sed '/HTTP_STATUS:/d')

  if [[ "${http_code}" == "200" ]]; then
    local total
    total=$(echo "${body}" | jq -r '.total // "unknown"' 2>/dev/null || echo "parse error")
    success "DocumentReference bundle received — total: ${total}"

    local output_file="${REPO_ROOT}/data/sample_fhir_notes.json"
    mkdir -p "${REPO_ROOT}/data"
    echo "${body}" | jq '.' > "${output_file}" 2>/dev/null || true
    info "Sample response saved to ${output_file}"

    # Pretty print first entry
    local first_id
    first_id=$(echo "${body}" | jq -r '.entry[0].resource.id // "none"' 2>/dev/null || echo "none")
    info "First DocumentReference ID: ${first_id}"
  elif [[ "${http_code}" == "403" ]]; then
    warn "403 Forbidden — add 'DocumentReference.read' to EPIC_SCOPES and re-run"
  elif [[ "${http_code}" == "401" ]]; then
    error "401 Unauthorized — token may be invalid or expired"
  else
    warn "HTTP ${http_code} from DocumentReference endpoint"
  fi
}

test_patient_search() {
  info "Testing Patient/${'$'}search (sandbox demo patient) …"

  # Epic sandbox test patient
  local test_patient_id="eJzlzOBpGAOqA.RDEiQDNxQ3"
  local url="${EPIC_FHIR_BASE_URL}/Patient/${test_patient_id}"

  local http_code
  http_code=$(curl --silent --output /dev/null --write-out "%{http_code}" \
    --max-time 15 \
    "${url}" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" \
    -H "Accept: application/fhir+json") || true

  if [[ "${http_code}" == "200" ]]; then
    success "Patient resource accessible (sandbox test patient found)"
  elif [[ "${http_code}" == "404" ]]; then
    info "Test patient not found — expected in non-sandbox environments"
  else
    warn "HTTP ${http_code} from Patient endpoint"
  fi
}

print_connection_summary() {
  echo ""
  echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
  echo -e "${BOLD} Epic FHIR R4 Connection Summary${NC}"
  echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
  echo -e "  FHIR Version : ${CYAN}${EPIC_FHIR_VERSION}${NC}"
  echo -e "  Base URL     : ${CYAN}${EPIC_FHIR_BASE_URL}${NC}"
  echo -e "  Client ID    : ${CYAN}${EPIC_CLIENT_ID:0:8}…${NC}"
  echo -e "  Scopes       : ${CYAN}${EPIC_SCOPES}${NC}"
  [[ -n "${EPIC_ORG_ID:-}" ]] && echo -e "  Org ID       : ${CYAN}${EPIC_ORG_ID}${NC}"
  echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
  echo ""
  echo -e "${GREEN}Setup complete.${NC} Add the following to your application's environment:"
  echo ""
  echo "  export EPIC_CLIENT_ID=\"${EPIC_CLIENT_ID}\""
  echo "  export EPIC_FHIR_BASE_URL=\"${EPIC_FHIR_BASE_URL}\""
  echo "  export EPIC_TOKEN_URL=\"${EPIC_TOKEN_URL}\""
  echo "  export EPIC_SCOPES=\"${EPIC_SCOPES}\""
  echo ""
}

# ── Main ──────────────────────────────────────────────────────────────────────

main() {
  info "Starting Epic FHIR R4 setup (test-only=${TEST_ONLY})"

  if ! load_env_file && [[ "${TEST_ONLY}" == "false" ]]; then
    prompt_credentials
    save_env_file
    ensure_gitignore
  elif [[ "${TEST_ONLY}" == "true" ]] && ! load_env_file; then
    die "No credentials found. Run without --test-only to configure."
  fi

  # Validate required vars
  : "${EPIC_CLIENT_ID:?EPIC_CLIENT_ID is not set}"
  : "${EPIC_CLIENT_SECRET:?EPIC_CLIENT_SECRET is not set}"
  : "${EPIC_FHIR_BASE_URL:?EPIC_FHIR_BASE_URL is not set}"
  : "${EPIC_TOKEN_URL:?EPIC_TOKEN_URL is not set}"

  load_cached_token || fetch_access_token

  test_capability_statement
  pull_sample_patient_notes
  test_patient_search
  print_connection_summary
}

main "$@"
